language: cpp
dist: trusty
sudo: required

matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
            - yasm
      before_install:
        - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - yasm
      before_install:
        - sudo update-alternatives --install /usr/bin/clang clang /usr/bin/clang-4.0 60 --slave /usr/bin/clang++ clang++ /usr/bin/clang++-4.0

install:
  - git clone git://git.videolan.org/ffmpeg.git --depth=1 ffmpeg
  - cd ffmpeg
  - ./configure --disable-avfilter --disable-devices --disable-doc --disable-encoders --disable-filters --disable-hwaccels --disable-muxers --disable-network
  - make -j2
  - sudo make install
  - cd ..
script:
  - ./autogen.sh --enable-static --disable-shared || cat config.log
  - make V=1 CXXFLAGS='-Werror -Wno-error=deprecated-declarations' -j2 -k
notifications:
  email:
    - on_success: change
    - on_failure: change
